import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../../components/navbar";

export const metadata: Metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
